# Generated by Django 4.2 on 2023-04-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neibhorhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_status', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.CharField(max_length=50)),
                ('bedroom', models.IntegerField()),
                ('number_car_garage', models.IntegerField()),
                ('fire_place', models.BooleanField(default=True)),
                ('year_built', models.IntegerField()),
                ('build_up_size', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('property_photo1', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('property_photo2', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('property_photo3', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('property_photo4', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_searched', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighbhorhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.neibhorhood')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.pricerange')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=True)),
                ('neighbhorhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.neibhorhood')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.pricerange')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('personal_inf', models.CharField(max_length=255)),
                ('personal_photo', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),

]
