# Generated by Django 4.2 on 2023-05-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_alter_propertydetails_property_photo1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/% Y/% m/% d/"
                    ),
                ),
                ("personal_inf", models.CharField(max_length=255)),
            ],
        ),
    ]
