# Generated by Django 4.2 on 2023-05-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_myprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Neibhorhood",
            new_name="Neighborhood",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="neighbhorhood",
            new_name="neighborhood",
        ),
        migrations.RenameField(
            model_name="searches",
            old_name="neighbhorhood",
            new_name="neighborhood",
        ),
    ]
