# Generated by Django 4.2 on 2023-05-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_rename_neibhorhood_neighborhood_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myprofile",
            old_name="personal_inf",
            new_name="My_Profile",
        ),
    ]
