# Generated by Django 4.2 on 2023-05-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_rename_personal_inf_myprofile_my_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Property",
            new_name="Property_search",
        ),
    ]
