# Generated by Django 4.2 on 2023-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_rename_property_property_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
    ]
