# Generated by Django 4.2 on 2023-05-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetails",
            name="property_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.availability"
            ),
        ),
    ]
