# Generated by Django 4.2 on 2023-05-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_alter_propertydetails_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydetails",
            name="property_status",
            field=models.CharField(max_length=50),
        ),
    ]
