# Generated by Django 4.2 on 2023-05-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0010_alter_propertydetails_property_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Availability",
        ),
    ]
