# Generated by Django 4.2 on 2023-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0011_delete_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="property_search",
            name="date_searched",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name="Searches",
        ),
    ]
