# Generated by Django 4.2 on 2023-05-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_rename_propertydetails_propertydetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyavailability",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
