# Generated by Django 4.2 on 2023-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0014_alter_propertyavailability_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertydetail",
            old_name="propert",
            new_name="Property_searchs",
        ),
        migrations.AlterField(
            model_name="propertydetail",
            name="property_status",
            field=models.BooleanField(default=True),
        ),
    ]
