# Generated by Django 4.2 on 2023-05-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0015_rename_propert_propertydetail_property_searchs_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PropertyDetail",
            new_name="PropertyList",
        ),
    ]
